version: "3.9"
services:
  db:
    container_name: "lib-bun-express"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=library-bun-express
    volumes:
      - libdata:/var/lib/postgresql/data/libdata
    image: postgres
    ports:
      - 5432:5432
volumes:
  libdata: